[master]
# Remplacer par l'IP du master_public_ip outputée par terraform
<MASTER_PUBLIC_IP> ansible_user=azureuser

[worker]
# Remplacer par l'IP du worker_public_ip outputée par terraform
<WORKER_PUBLIC_IP> ansible_user=azureuser

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
k3s_master_ip="<MASTER_PRIVATE_IP>" # Remplacer par master_private_ip outputé par terraform
