[master]
# Remplacer par l'IP du master_public_ip outputée par terraform
20.107.200.206 ansible_user=azureuser

[worker]
# Remplacer par l'IP du worker_public_ip outputée par terraform
52.236.51.201 ansible_user=azureuser

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
k3s_master_ip="10.0.1.4" # Remplacer par master_private_ip outputé par terraform
ansible_ssh_private_key_file="~/.ssh/id_rsa"
